# Generated by Django 4.1.1 on 2023-03-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngoapp', '0003_user_reg'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_reg',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
