# Generated by Django 4.1.1 on 2023-03-28 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ngoapp', '0005_donation'),
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=150)),
                ('pdes', models.CharField(max_length=1000)),
                ('amount', models.CharField(max_length=150)),
                ('photo', models.ImageField(null=True, upload_to='')),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngoapp.ngo_reg')),
            ],
        ),
    ]
