# Generated by Django 4.1.1 on 2023-03-29 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngoapp', '0007_udonation_assigneddonation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='udonation',
        ),
    ]
