# Generated by Django 4.1.1 on 2023-03-29 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngoapp', '0009_udonation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='ngo',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='udonation',
            name='ngo',
        ),
        migrations.RemoveField(
            model_name='udonation',
            name='project',
        ),
        migrations.RemoveField(
            model_name='udonation',
            name='user',
        ),
        migrations.DeleteModel(
            name='assigneddonation',
        ),
        migrations.DeleteModel(
            name='donation',
        ),
        migrations.DeleteModel(
            name='udonation',
        ),
    ]
