# Generated by Django 4.1.1 on 2023-03-29 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngoapp', '0011_udonation_assigneddonation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='assigneddonation',
        ),
    ]
