# Generated by Django 4.1.1 on 2023-03-29 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ngoapp', '0012_delete_assigneddonation'),
    ]

    operations = [
        migrations.CreateModel(
            name='assigneddonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=150)),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngoapp.udonation')),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngoapp.ngo_reg')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngoapp.project')),
            ],
        ),
    ]
