# Generated by Django 4.1.1 on 2023-03-29 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ngoapp', '0015_udonation_assigneddonation'),
    ]

    operations = [
        migrations.CreateModel(
            name='expenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etype', models.CharField(max_length=150)),
                ('amount', models.CharField(max_length=150)),
                ('edes', models.CharField(max_length=1500)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngoapp.project')),
            ],
        ),
    ]
